### ISSUE TITLE
Octocat graphic is off-center

### ISSUE THREAD

**Issue by zeke** [npmhub/npmhub.org#6]
cc @bfred-it 

![Screen Shot 2019-03-19 at 11 04 08 AM](https://user-images.githubusercontent.com/2289/54630331-c8db1080-4a36-11e9-89ef-ec99273abffc.png)

**Comment by bfred-it** [comment]
Fixed. Can you force the site to be on https and change the link on https://github.com/npmhub/npmhub to be https?

**Comment by zeke** [comment]
Done and done. 👍

**Comment by bfred-it** [comment]
Cool! I also updated the header link in https://github.com/npmhub/npmhub.org now
